### ISSUE TITLE
Hijri Date

### ISSUE THREAD

**Issue by hjcccompany** [Jessewb786/Silaty#8] opened 2018-11-30 17:37 UTC
I have rarely coded in python, so that's why I can't help you right now in codes.
The problem here goes in the Hijri date, even with that Algorithm it sometimes goes wrong for example by one day missing.

I think adding the option for that day in the options menu will help a lot.

Thanks for your work, I really like the app, and I will soon Inshaa Allah help you improving it.
Omar E.

**Comment by AXeL-dev** [comment] 2018-12-02 16:15
Hey,

it will be more useful if you can provide some screenshots with the steps you have done so i/we can reproduce the issue, for example: where the issue happens exactly? in which month? ..

`I think adding the option for that day in the options menu will help a lot.`

well, we need to investigate first about the reason of the issue, then we may take a decision about how to fix it x).

Finally, you're welcome.

**Comment by hjcccompany** [comment] 2018-12-04 15:35
like for example today date is wrong, its 26/03/1440 but in the SIlaty software its past a day (25/03) you can check that.

**Comment by hjcccompany** [comment] 2018-12-04 19:03
to explain more,
We are working with moon date(s) not Sun date(s), so there is 2 solutions I think.
1) Is to make it like prayer time, get (sync) it from internet
2)Make an option to correct date if its wrong by 1 day + or -.

and thanks a lot for what you did, this app helped me a lot.
May Allah make it in your rewards brother

**Comment by AXeL-dev** [comment] 2018-12-04 20:58
Inshalah x).

Also, i'm okay with the second solution because it seems more easy to implement, i guess.

There is also a fast solution by modifying the value in the line below to `227014`, which will add one day to the hijri calendar
https://github.com/Jessewb786/Silaty/blob/8df0ce19c2a6580185e9f8443803c78e1539718b/hijra.py#L54

unfortunately this value seems to be constant so i'll keep thinking about how to implement the +/-1 day option..

**Comment by hjcccompany** [comment] 2018-12-04 21:38
or don't worry, I will do it soon when I got some time : ) , and make a pull request
جزاك الله خيرا

**Comment by AXeL-dev** [comment] 2018-12-05 14:55
fixed on 4f7f46230a7fe875a7ee42bdd01108a91c2b91f3

You can test it using my fork https://github.com/AXeL-dev/Silaty

P.S.: the debian package is not yet updated so you may need to Install it from source.

**Closed as completed** 2021-06-06 10:33 UTC
